# Generated by Django 4.1.1 on 2022-10-08 15:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xinwen', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='xinwen',
            name='add_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 10, 8, 23, 13, 53, 169537), verbose_name='add time'),
        ),
    ]
