# Generated by Django 4.1.1 on 2022-10-08 15:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xinwen', '0002_xinwen_add_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='xinwen',
            name='img_url',
            field=models.ImageField(default=111, upload_to='imgurl/', verbose_name='Image address'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='xinwen',
            name='add_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 10, 8, 23, 28, 26, 564820), verbose_name='Add_Time'),
        ),
        migrations.AlterField(
            model_name='xinwen',
            name='biaoti',
            field=models.CharField(max_length=100, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='xinwen',
            name='neirong',
            field=models.CharField(max_length=1000, verbose_name='Aontent'),
        ),
        migrations.AlterField(
            model_name='xinwen',
            name='zuozhe',
            field=models.CharField(max_length=20, verbose_name='Author'),
        ),
    ]
