# Generated by Django 4.1.1 on 2022-10-08 16:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xinwen', '0003_xinwen_img_url_alter_xinwen_add_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='xinwen',
            name='add_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 10, 9, 0, 33, 12, 336809), verbose_name='Add_Time'),
        ),
        migrations.AlterField(
            model_name='xinwen',
            name='img_url',
            field=models.ImageField(upload_to='img_url/', verbose_name='Image address'),
        ),
        migrations.AlterField(
            model_name='xinwen',
            name='neirong',
            field=models.CharField(max_length=1000, verbose_name='Content'),
        ),
    ]
