# Generated by Django 4.1.1 on 2022-10-09 15:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xinwen', '0006_alter_xinwen_add_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='xinwen',
            name='add_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 10, 9, 23, 47, 1, 982876), verbose_name='Add_Time'),
        ),
    ]
