# Generated by Django 4.1.1 on 2022-10-09 16:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xinwen', '0007_alter_xinwen_add_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='xinwen',
            name='add_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 10, 10, 0, 41, 22, 634452), verbose_name='Add_Time'),
        ),
    ]
