# Generated by Django 4.1.1 on 2022-10-10 15:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xinwen', '0009_alter_xinwen_add_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='xinwen',
            name='add_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 10, 10, 23, 53, 58, 249133), verbose_name='Add_Time'),
        ),
    ]
