# Generated by Django 4.1.1 on 2022-10-10 16:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xinwen', '0010_alter_xinwen_add_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='xinwen',
            name='add_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 10, 11, 0, 14, 45, 832878), verbose_name='Add_Time'),
        ),
    ]
