# Generated by Django 4.1.2 on 2022-10-14 16:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("xinwen", "0015_alter_xinwen_add_time"),
    ]

    operations = [
        migrations.AlterField(
            model_name="xinwen",
            name="add_time",
            field=models.DateTimeField(
                default=datetime.datetime(2022, 10, 15, 0, 44, 3, 809960),
                verbose_name="Add_Time",
            ),
        ),
    ]
