# Generated by Django 4.1.1 on 2022-10-09 15:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='newposts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Title')),
                ('add_time', models.DateTimeField(default=datetime.datetime(2022, 10, 9, 23, 16, 54, 584673), verbose_name='Add_Time')),
            ],
        ),
    ]
