# Generated by Django 4.1.1 on 2022-10-09 15:28

import ckeditor.fields
import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newposts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='newposts',
            name='content',
            field=ckeditor.fields.RichTextField(default=1, verbose_name='basic rich text'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='newposts',
            name='add_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 10, 9, 23, 28, 20, 79009), verbose_name='Add_Time'),
        ),
    ]
