# Generated by Django 4.1.1 on 2022-10-09 15:47

import ckeditor_uploader.fields
import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newposts', '0002_newposts_content_alter_newposts_add_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='newposts',
            name='all_content',
            field=ckeditor_uploader.fields.RichTextUploadingField(default=1, verbose_name='fruitful rich text'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='newposts',
            name='add_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 10, 9, 23, 47, 2, 47529), verbose_name='Add_Time'),
        ),
    ]
