# Generated by Django 4.1.1 on 2022-10-09 16:41

import ckeditor.fields
import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newposts', '0003_newposts_all_content_alter_newposts_add_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='simdposts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Title')),
                ('all_content', ckeditor.fields.RichTextField(verbose_name='simdposts rich text')),
            ],
        ),
        migrations.AlterField(
            model_name='newposts',
            name='add_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 10, 10, 0, 41, 22, 698466), verbose_name='Add_Time'),
        ),
    ]
