# Generated by Django 4.1.1 on 2022-10-09 16:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newposts', '0004_simdposts_alter_newposts_add_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='simdposts',
            name='add_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 10, 10, 0, 45, 20, 869886), verbose_name='simd_Add_Time'),
        ),
        migrations.AlterField(
            model_name='newposts',
            name='add_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 10, 10, 0, 45, 20, 869886), verbose_name='Add_Time'),
        ),
    ]
