# Generated by Django 4.1.1 on 2022-10-10 16:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newposts', '0006_simdfiles_alter_newposts_add_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='simdfiles',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='file_url/', verbose_name='Image Upload address'),
        ),
        migrations.AlterField(
            model_name='newposts',
            name='add_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 10, 11, 0, 14, 45, 903873), verbose_name='Add_Time'),
        ),
        migrations.AlterField(
            model_name='simdfiles',
            name='add_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 10, 11, 0, 14, 45, 904873), verbose_name='File added time'),
        ),
        migrations.AlterField(
            model_name='simdposts',
            name='add_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 10, 11, 0, 14, 45, 904873), verbose_name='simd_Add_Time'),
        ),
    ]
