# Generated by Django 4.1.1 on 2022-10-10 16:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newposts', '0008_simdfiles_name_alter_newposts_add_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='simdfiles',
            name='ceshi',
            field=models.CharField(choices=[('1', 'Original Content'), ('2', 'not Original'), ('3', 'bu zhi dao')], default='1', max_length=50, verbose_name='default optional parameters'),
        ),
        migrations.AlterField(
            model_name='newposts',
            name='add_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 10, 11, 0, 25, 58, 117433), verbose_name='Add_Time'),
        ),
        migrations.AlterField(
            model_name='simdfiles',
            name='add_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 10, 11, 0, 25, 58, 118433), verbose_name='File added time'),
        ),
        migrations.AlterField(
            model_name='simdposts',
            name='add_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 10, 11, 0, 25, 58, 118433), verbose_name='simd_Add_Time'),
        ),
    ]
