# Generated by Django 4.1.1 on 2022-10-10 16:36

import datetime
from django.db import migrations, models
import simditor.fields


class Migration(migrations.Migration):

    dependencies = [
        ('newposts', '0009_simdfiles_ceshi_alter_newposts_add_time_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='new category')),
                ('add_time', models.DateTimeField(default=datetime.datetime(2022, 10, 11, 0, 36, 27, 285171), verbose_name='news release time')),
            ],
        ),
        migrations.CreateModel(
            name='NewsPosts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100, null=True, verbose_name='Title')),
                ('all_content', simditor.fields.RichTextField(verbose_name='simdposts rich text')),
                ('add_time', models.DateTimeField(default=datetime.datetime(2022, 10, 11, 0, 36, 27, 285171), verbose_name='simd_Add_Time')),
            ],
        ),
        migrations.AlterField(
            model_name='newposts',
            name='add_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 10, 11, 0, 36, 27, 284158), verbose_name='Add_Time'),
        ),
        migrations.AlterField(
            model_name='simdfiles',
            name='add_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 10, 11, 0, 36, 27, 285171), verbose_name='File added time'),
        ),
        migrations.AlterField(
            model_name='simdposts',
            name='add_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 10, 11, 0, 36, 27, 285171), verbose_name='simd_Add_Time'),
        ),
    ]
